# Generated by Django 3.1 on 2020-08-22 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener_app', '0002_auto_20200822_1248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urlmodel',
            old_name='url_click_client',
            new_name='url_click_clients',
        ),
    ]
